# Web Scraping to Populate SQL Database

In [1]:
import pandas as pd
import os
import requests
from bs4 import BeautifulSoup
from datetime import datetime
from pandas.tseries.offsets import DateOffset
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.simplefilter(action = 'ignore', category = FutureWarning)

sym = input('Input stock ticker ')
url = 'http://openinsider.com/screener?s='+sym+'&o=&pl=&ph=&ll=&lh=&fd=730&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xp=1&xs=1&vl=&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=0&cnt=100&page=1'
      
# figure out how to make the requests automated, and scraping the URL while passing in certain companies.

Input stock ticker GOOGL

In [2]:
df = pd.read_html(url, skiprows = 1, header = 0)

In [3]:
df = df[6]
df.drop(['Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15' ], inplace = True, axis = 1)
row_zero = df.columns

In [4]:
column_names = ['Type','FilingDate','TradeDate','Ticker','InsiderName', 'Title', 'TradeType', 'Price','Qty','Owned',
               'OwnPctChange', 'Value']

df.columns = column_names

df["Type"] = df['Type'].fillna('S')

In [5]:
data = []


data.insert(0,{'Type': row_zero[0] ,'FilingDate' : row_zero[1] ,'TradeDate' : row_zero[2],'Ticker' : row_zero[3] ,'InsiderName' : row_zero[4], 'Title' : row_zero[5], 'TradeType' : row_zero[6], 'Price' : row_zero[7],'Qty' : row_zero[8],'Owned' : row_zero[9],'OwnPctChange' : row_zero[10], 'Value': row_zero[11]})

p = pd.DataFrame(data)

p['Qty'] = p['Qty'].str.replace(',', '').astype(int)
p['Owned'] = p['Owned'].str.replace(',', '').astype(int)

In [6]:
df = pd.concat([p, df], ignore_index=True)
df

,Type,FilingDate,TradeDate,Ticker,InsiderName,Title,TradeType,Price,Qty,Owned,OwnPctChange,Value
0,D,2021-12-15 19:24:31,2021-12-15,GOOG,Pichai Sundar,CEO,S - Sale+OE,"$2,866.25",-3000,102836,-3%,"-$8,598,736"
1,D,2021-12-10 21:28:22,2021-12-09,GOOG,Page Lawrence,"Dir, 10%",S - Sale+OE,"$2,971.24",-13889,19680280,0%,"-$41,267,519"
2,D,2021-12-10 20:29:04,2021-12-09,GOOG,Page Lawrence,"Dir, 10%",S - Sale+OE,"$2,960.73",-13889,0,-100%,"-$41,121,590"
3,D,2021-12-09 20:06:40,2021-12-08,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,"$2,960.67",-13889,18815901,0%,"-$41,120,797"
4,D,2021-12-09 19:16:48,2021-12-08,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,"$2,945.80",-13889,0,-100%,"-$40,914,201"
...,...,...,...,...,...,...,...,...,...,...,...,...
95,S,2021-08-02 17:50:14,2021-08-02,GOOG,Mather Ann,Dir,S - Sale,"$2,709.69",-18,1840,-1%,"-$48,774"
96,D,2021-08-02 17:31:59,2021-07-29,GOOG,Page Lawrence,"Dir, 10%",S - Sale+OE,"$2,733.78",-13888,19888614,0%,"-$37,966,724"
97,D,2021-08-02 16:31:09,2021-07-29,GOOG,Page Lawrence,"Dir, 10%",S - Sale+OE,"$2,719.69",-13888,0,-100%,"-$37,771,018"
98,D,2021-07-30 16:21:51,2021-07-28,GOOG,Page Lawrence,"Dir, 10%",S - Sale+OE,"$2,772.31",-4113,19902502,0%,"-$11,402,515"
99,S,2021-07-30 16:19:49,2021-07-28,GOOG,Page Lawrence,"Dir, 10%",S - Sale,"$2,747.77",-11376,19905015,0%,"-$31,258,601"

In [7]:
# clean up dateframe types, drop symbols that affect floats and integers. 

df['Price'] = df['Price'].str.replace('$', '').str.replace(',', '').astype(float)
df['Value'] = df['Value'].str.replace('$', '').str.replace(',', '').astype(int)


df['OwnPctChange'] = df['OwnPctChange'].str.replace('%', '').astype(int)
df['FilingDate'] = pd.to_datetime(df['FilingDate'])
df['TradeDate'] = pd.to_datetime(df['TradeDate'])
df[['Type', 'Ticker', 'InsiderName', 'Title', 'Trade-Type']] = df[['Type', 'Ticker', 'InsiderName', 'Title', 'TradeType']].astype(str)
df = df.drop('Trade-Type', 1)

In [8]:
insiders = df
insiders

,Type,FilingDate,TradeDate,Ticker,InsiderName,Title,TradeType,Price,Qty,Owned,OwnPctChange,Value
0,D,2021-12-15 19:24:31,2021-12-15,GOOG,Pichai Sundar,CEO,S - Sale+OE,2866.25,-3000,102836,-3,-8598736
1,D,2021-12-10 21:28:22,2021-12-09,GOOG,Page Lawrence,"Dir, 10%",S - Sale+OE,2971.24,-13889,19680280,0,-41267519
2,D,2021-12-10 20:29:04,2021-12-09,GOOG,Page Lawrence,"Dir, 10%",S - Sale+OE,2960.73,-13889,0,-100,-41121590
3,D,2021-12-09 20:06:40,2021-12-08,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2960.67,-13889,18815901,0,-41120797
4,D,2021-12-09 19:16:48,2021-12-08,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2945.80,-13889,0,-100,-40914201
...,...,...,...,...,...,...,...,...,...,...,...,...
95,S,2021-08-02 17:50:14,2021-08-02,GOOG,Mather Ann,Dir,S - Sale,2709.69,-18,1840,-1,-48774
96,D,2021-08-02 17:31:59,2021-07-29,GOOG,Page Lawrence,"Dir, 10%",S - Sale+OE,2733.78,-13888,19888614,0,-37966724
97,D,2021-08-02 16:31:09,2021-07-29,GOOG,Page Lawrence,"Dir, 10%",S - Sale+OE,2719.69,-13888,0,-100,-37771018
98,D,2021-07-30 16:21:51,2021-07-28,GOOG,Page Lawrence,"Dir, 10%",S - Sale+OE,2772.31,-4113,19902502,0,-11402515
99,S,2021-07-30 16:19:49,2021-07-28,GOOG,Page Lawrence,"Dir, 10%",S - Sale,2747.77,-11376,19905015,0,-31258601

# Write Stock and Insider Data to Database

In [9]:
import sqlalchemy
password = os.environ.get('LAPTOP_PASS')

sym = sym.upper()
stock = pd.read_csv(sym+'_df.csv')

engine = sqlalchemy.create_engine('mysql+pymysql://root:'+str(password)+'@localhost:3306/Stock_DB')
engine

Engine(mysql+pymysql://root:***@localhost:3306/Stock_DB)

In [10]:
insiders.to_sql(
    name = 'insiders',
    con = engine,
    index = False,
    if_exists = 'replace'
)

In [11]:
stock.to_sql(
    name = 'stock',
    con = engine,
    index = False,
    if_exists = 'replace'
)

# SQL Queries

In [12]:
print(stock.columns)
print(insiders.columns)

Index(['GainLoss', 'DayOfWeek', 'Date', 'Open', 'Close', 'PctChange', 'High',
       'Low', 'HLVolatility', '50ema', '200ema', 'Volume', 'bull_bear'],
      dtype='object')
Index(['Type', 'FilingDate', 'TradeDate', 'Ticker', 'InsiderName', 'Title',
       'TradeType', 'Price', 'Qty', 'Owned', 'OwnPctChange', 'Value'],
      dtype='object')

In [35]:
query ='''

SELECT * from insiders
WHERE InsiderName = 'Brin Sergey'; 

'''

In [70]:
brin_sergey = pd.read_sql(query, engine)
brin_sergey

,Type,FilingDate,TradeDate,Ticker,InsiderName,Title,TradeType,Price,Qty,Owned,OwnPctChange,Value
0,D,2021-12-09 20:06:40,2021-12-08,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2960.67,-13889,18815901,0,-41120797
1,D,2021-12-09 19:16:48,2021-12-08,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2945.80,-13889,0,-100,-40914201
2,D,2021-12-08 12:15:17,2021-12-07,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2954.97,-1769,18829790,0,-5227338
3,D,2021-12-08 12:14:03,2021-12-07,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2947.71,-12989,18830690,0,-38287783
4,D,2021-12-08 12:12:05,2021-12-07,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2934.11,-13020,18830659,0,-38202167
5,D,2021-12-07 17:11:19,2021-12-06,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2871.40,-11775,18843679,0,-33810693
6,D,2021-12-07 17:08:49,2021-12-06,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2842.67,-7763,18849805,0,-22067636
7,D,2021-12-07 17:04:54,2021-12-06,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2832.98,-8240,5649,-59,-23343757
8,D,2021-11-12 12:48:30,2021-11-10,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2951.55,-7214,18910268,0,-21292500
9,D,2021-11-12 12:42:52,2021-11-10,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2937.80,-10819,18913338,0,-31784060
10,D,2021-11-12 12:33:10,2021-11-10,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2924.80,-9745,4144,-70,-28502172
11,D,2021-11-12 12:29:29,2021-11-09,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2968.52,-13889,0,-100,-41229803
12,S,2021-11-10 21:29:47,2021-11-09,GOOG,Brin Sergey,"Dir, 10%",S - Sale,2977.68,-13889,18924157,0,-41356985
13,D,2021-11-09 20:31:05,2021-11-08,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2995.86,-13889,18938046,0,-41609565
14,D,2021-11-09 19:52:37,2021-11-08,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2986.79,-13889,0,-100,-41483568
15,D,2021-10-15 11:41:12,2021-10-13,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2755.34,-13888,18951935,0,-38266200
16,D,2021-10-15 11:38:44,2021-10-13,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2752.11,-13888,0,-100,-38221260
17,D,2021-10-14 16:58:34,2021-10-12,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2739.37,-13889,0,-100,-38047136
18,D,2021-10-14 16:52:26,2021-10-12,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2742.11,-13889,18965823,0,-38085133
19,D,2021-10-12 19:30:45,2021-10-11,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2798.28,-13889,18979712,0,-38865376
20,D,2021-10-12 17:54:37,2021-10-11,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2800.66,-13889,18979712,0,-38898343
21,D,2021-09-13 19:24:52,2021-09-09,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2902.09,-13889,18993601,0,-40307198
22,D,2021-09-13 19:00:09,2021-09-09,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2876.30,-13889,18993601,0,-39948974
23,D,2021-09-10 12:41:03,2021-09-08,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2897.32,-13889,19007490,0,-40240838
24,D,2021-09-10 12:12:26,2021-09-08,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2871.76,-13889,19007490,0,-39885808
25,D,2021-09-08 21:01:14,2021-09-07,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2908.08,-13889,19021379,0,-40390311
26,D,2021-09-08 20:29:24,2021-09-07,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2883.29,-13889,19020779,0,-40046008
27,D,2021-08-11 20:37:45,2021-08-11,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2733.61,-13889,19061868,0,-37967095
28,D,2021-08-11 20:12:35,2021-08-11,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2757.27,-13889,19061868,0,-38295788
29,D,2021-08-11 15:05:24,2021-08-10,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2760.28,-13889,19075757,0,-38337557
30,D,2021-08-11 14:13:03,2021-08-10,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2739.39,-13889,19075757,0,-38047364
31,D,2021-08-10 13:23:28,2021-08-09,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2748.37,-13889,19089646,0,-38172090
32,D,2021-08-10 12:19:16,2021-08-09,GOOG,Brin Sergey,"Dir, 10%",S - Sale+OE,2724.78,-13889,0,-100,-37844447

In [72]:
brin_sergey.rename(columns={'TradeDate':'Date'}, inplace=True)
brin_sergey['Date'] = brin_sergey['Date'].astype(str)
stock['Date'] = stock['Date'].astype(str)

In [78]:
df_test = pd.merge(stock, brin_sergey, on = 'Date')

In [81]:
df_test[['Close', 'Date']]

      Close        Date
0   2963.73  2021-12-08
1   2963.73  2021-12-08
2   2945.39  2021-12-07
3   2945.39  2021-12-07
4   2945.39  2021-12-07
5   2863.10  2021-12-06
6   2863.10  2021-12-06
7   2863.10  2021-12-06
8   2917.87  2021-11-10
9   2917.87  2021-11-10
10  2917.87  2021-11-10
11  2978.37  2021-11-09
12  2978.37  2021-11-09
13  2980.62  2021-11-08
14  2980.62  2021-11-08
15  2751.64  2021-10-13
16  2751.64  2021-10-13
17  2728.98  2021-10-12
18  2728.98  2021-10-12
19  2778.28  2021-10-11
20  2778.28  2021-10-11
21  2870.82  2021-09-09
22  2870.82  2021-09-09
23  2873.82  2021-09-08
24  2873.82  2021-09-08
25  2885.61  2021-09-07
26  2885.61  2021-09-07
27  2725.58  2021-08-11
28  2725.58  2021-08-11
29  2736.14  2021-08-10
30  2736.14  2021-08-10
31  2738.26  2021-08-09
32  2738.26  2021-08-09

In [82]:
def narrow_down_between(n, n_2):
    movement = stock_df.loc[(stock_df['Date'] >= n) & (stock_df['PctChange'] <= n_2)]

,GainLoss,DayOfWeek,Date,Open,Close,PctChange,High,Low,HLVolatility,50ema,200ema,Volume,bull_bear
0,-2.358035,Monday,2021-12-20,2800.00,2832.140,-0.083260,2835.490,2786.4200,49.0700,2890.2718,2585.59935,1343608.0,0
1,-53.375610,Friday,2021-12-17,2850.00,2834.500,-1.883070,2876.690,2826.0000,50.6900,2889.5432,2581.47615,2550894.0,0
2,-39.375888,Thursday,2021-12-16,2943.41,2888.900,-1.363006,2953.535,2872.1400,81.3950,2888.5432,2577.78900,1682519.0,0
3,51.572404,Wednesday,2021-12-15,2868.18,2928.820,1.760859,2934.420,2833.5578,100.8622,2885.7912,2573.51415,1818523.0,0
4,-37.884676,Tuesday,2021-12-14,2879.36,2878.140,-1.316290,2889.600,2824.2950,65.3050,2881.6240,2568.92710,1922312.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4361,1.142176,Wednesday,2004-08-25,104.76,106.000,1.077525,108.000,103.8800,4.1200,NaN,NaN,9188600.0,0
4362,-4.342423,Tuesday,2004-08-24,111.24,104.870,-4.140768,111.600,103.5700,8.0300,NaN,NaN,15247300.0,1
4363,1.100969,Monday,2004-08-23,110.76,109.400,1.006371,113.480,109.0500,4.4300,NaN,NaN,18256100.0,1
4364,8.608883,Friday,2004-08-20,101.01,108.310,7.948373,109.080,100.5000,8.5800,NaN,NaN,22834300.0,0
4365,NaN,Thursday,2004-08-19,100.01,100.335,NaN,104.060,95.9600,8.1000,NaN,NaN,44659000.0,1

In [ ]:
engine.dispose()

In [ ]:
# make relevant joins with insider and stock table to reveal patterns.

In [ ]:
# script automated with crontab, runs at 5 PM Monday - Friday all year long. 
# 0 17 * * 1-5 cd Desktop && Python Web_Scraping_Read_HTML.py >> test.txt 

# df.to_csv('/Users/sammarcustaylor/Desktop/Stocks/BA_data.csv', index = False)